BEGIN;

DROP SCHEMA IF EXISTS Waste CASCADE;
CREATE SCHEMA Waste;
SET search_path TO Waste;

SET client_encoding = 'LATIN1';

CREATE TABLE WasteType (
    wasteType CHARACTER(1) NOT NULL UNIQUE
);

CREATE TABLE TruckType (
    truckType CHARACTER(1) NOT NULL UNIQUE,
    wasteType CHARACTER(1) NOT NULL
);

CREATE TABLE Truck (
    tID INTEGER NOT NULL,
    truckType CHARACTER(1) NOT NULL,
    capacity INTEGER NOT NULL
);

CREATE TABLE Facility (
    fID INTEGER NOT NULL,
    address TEXT NOT NULL,
    wasteType CHARACTER(1) NOT NULL
);

CREATE TABLE Employee (
    eID INTEGER NOT NULL,
    name TEXT NOT NULL,
    hireDate DATE NOT NULL
);

CREATE TABLE Driver (
    eID INTEGER NOT NULL,
    truckType CHARACTER(1) NOT NULL
);

CREATE TABLE Technician (
    eID INTEGER NOT NULL UNIQUE,
    truckType CHARACTER(1) NOT NULL
);

CREATE TABLE Maintenance (
    tID INTEGER NOT NULL,
    eID INTEGER NOT NULL,
    date DATE NOT NULL
);

CREATE TABLE Route (
    rID INTEGER NOT NULL,
    wasteType CHARACTER(1) NOT NULL,
    length INTEGER NOT NULL
);

CREATE TABLE Stop (
    address TEXT NOT NULL,
    rID INTEGER NOT NULL,
    assistance BOOLEAN NOT NULL
);

CREATE TABLE Trip (
    rid INTEGER NOT NULL,
    tID INTEGER NOT NULL,
    date DATE NOT NULL,
    volume INTEGER NOT NULL,
    eID1 INTEGER NOT NULL,
    eID2 INTEGER NOT NULL,
    fID INTEGER NOT NULL
);

ALTER TABLE ONLY WasteType ADD CONSTRAINT pkey_WasteType PRIMARY KEY (wasteType);
-- ALTER TABLE ONLY WasteType ADD CONSTRAINT fkey_WasteType_TruckType FOREIGN KEY (wasteType) REFERENCES TruckType (wasteType);
-- ALTER TABLE ONLY WasteType ADD CONSTRAINT fkey_WasteType_Facility FOREIGN KEY (wasteType) REFERENCES Facility (wasteType);

ALTER TABLE ONLY TruckType
ADD CONSTRAINT pkey_TruckType PRIMARY KEY (truckType, wasteType);
ALTER TABLE ONLY TruckType
ADD CONSTRAINT fkey_TruckType_WasteType FOREIGN KEY (wasteType) REFERENCES WasteType (wasteType);

ALTER TABLE ONLY Truck ADD CONSTRAINT pkey_Truck PRIMARY KEY (tID);
ALTER TABLE ONLY Truck ADD CONSTRAINT fkey_Truck_TruckType FOREIGN KEY (truckType) REFERENCES TruckType (truckType);

ALTER TABLE ONLY Facility ADD CONSTRAINT pkey_Facility PRIMARY KEY (fID);
ALTER TABLE ONLY Facility ADD CONSTRAINT fkey_Facility_WasteType FOREIGN KEY (wasteType) REFERENCES WasteType (wasteType);
-- ALTER TABLE ONLY Truck ADD CONSTRAINT fkey_Facility_Trip FOREIGN KEY (fID) REFERENCES Trip (fID);

ALTER TABLE ONLY Employee ADD CONSTRAINT pkey_Employee PRIMARY KEY (eID);

ALTER TABLE ONLY Driver ADD CONSTRAINT pkey_Driver PRIMARY KEY (eID, truckType);
ALTER TABLE ONLY Driver ADD CONSTRAINT fkey_Driver_Employee FOREIGN KEY (eID) REFERENCES Employee (eID);
ALTER TABLE ONLY Driver ADD CONSTRAINT fkey_Driver_TruckType FOREIGN KEY (truckType) REFERENCES TruckType (truckType);

ALTER TABLE ONLY Technician ADD CONSTRAINT pkey_Technician PRIMARY KEY (eID, truckType);
ALTER TABLE ONLY Technician ADD CONSTRAINT fkey_Technician_Employee FOREIGN KEY (eID) REFERENCES Employee (eID);
ALTER TABLE ONLY Technician ADD CONSTRAINT fkey_Technician_TruckType FOREIGN KEY (truckType) REFERENCES TruckType (truckType);

ALTER TABLE ONLY Maintenance ADD CONSTRAINT pkey_Maintenance PRIMARY KEY (tID, eID, date);
ALTER TABLE ONLY Maintenance ADD CONSTRAINT fkey_Maintenance_Truck FOREIGN KEY (tID) REFERENCES Truck (tID);
ALTER TABLE ONLY Maintenance ADD CONSTRAINT fkey_Maintenance_Technician FOREIGN KEY (eID) REFERENCES Technician (eID);

ALTER TABLE ONLY Route ADD CONSTRAINT pkey_Route PRIMARY KEY (rID);

ALTER TABLE ONLY Stop ADD CONSTRAINT pkey_Stop PRIMARY KEY (address, rID);
ALTER TABLE ONLY Stop ADD CONSTRAINT fkey_Stop_Route FOREIGN KEY (rID) REFERENCES Route (rID);

ALTER TABLE ONLY Trip ADD CONSTRAINT pkey_Trip PRIMARY KEY (rID, tID, date);
ALTER TABLE ONLY Trip ADD CONSTRAINT fkey_Trip_Route FOREIGN KEY (rID) REFERENCES Route (rID);
ALTER TABLE ONLY Trip ADD CONSTRAINT fkey_Trip_Truck FOREIGN KEY (tID) REFERENCES Truck (tID);
ALTER TABLE ONLY Trip ADD CONSTRAINT fkey_Trip_Driver FOREIGN KEY (eID1) REFERENCES Driver (eID);
ALTER TABLE ONLY Trip ADD CONSTRAINT fkey_Trip_Driver FOREIGN KEY (eID2) REFERENCES Driver (eID);
ALTER TABLE ONLY Trip ADD CONSTRAINT fkey_Trip_Facility FOREIGN KEY (fID) REFERENCES Facility (fID);

COMMIT;